prep-javascript-variables - Marianne Cuevas
mariannecuevas/prep-1122-code-solutions pull request #10
Opened 2022-11-22 08:05 UTC by mariannecuevas

![javscript variables](https://user-images.githubusercontent.com/117552789/203258943-7d52e299-21f9-4b2c-b1a2-86d182a4438f.png)

2022-11-22 15:53 UTC, thebearingedge requested changes

2022-11-22 15:53 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +    var numberofPets = '0';
For numbers, we'll want to leave off the quotes so that the JavaScript engine doesn't interpret them as strings.

2022-11-23 01:46 UTC, mariannecuevas commented
![javscript variables](https://user-images.githubusercontent.com/117552789/203454605-990a2256-f6f6-488e-ab01-44f95ab0cf39.png)

2022-11-23 02:12 UTC, thebearingedge approved these changes

2022-11-23 02:36 UTC, merged