prep-javascript-arrays - Marianne Cuevas
mariannecuevas/prep-1122-code-solutions pull request #12
Opened 2022-11-22 09:24 UTC by mariannecuevas

![javascript arrays](https://user-images.githubusercontent.com/117552789/203276185-9ae9d982-d2df-47e0-97bd-f4f613e14ad1.png)

2022-11-22 16:08 UTC, thebearingedge requested changes

2022-11-22 16:08 UTC, thebearingedge commented on prep-javascript-arrays/main.js
> +var lastElement = languages[5];
We can calculate the last index by subtracting 1 from the length

```js
var lastElement = languages[length - 1];
```

2022-11-23 01:51 UTC, mariannecuevas commented
![javascript arrays](https://user-images.githubusercontent.com/117552789/203455106-5bfccb94-f0b8-45a2-baac-f428d7beba97.png)

2022-11-23 02:17 UTC, thebearingedge approved these changes

2022-11-23 02:36 UTC, merged